---
title: "Blog post 1: Possible data sets"
author: "Group 10"
date: "2024-03-04"
date-modified: "2024-03-04"
draft: FALSE
---

**Option 1: Stanford Education Data Archive**

https://edopportunity.org/get-the-data/seda-archive-downloads/

  SEDA is a long-term project working to standardize state test scores in order to make them comparable between states. As each state implements their own statewide standardized tests for each grade level with different scoring scales, it is normally quite challenging to perform a direct comparison of differences between states. SEDA aims to resolve that, with available data on individual school performance all the way up to statewide performance, covering math and reading tests for multiple grade levels. We are thinking we would use district-level data, as that would allow for a lot of detailed work if we choose to focus on a specific region. They also have an extensive file of different covariates for each district with percentages of different racial groups, gender, poverty levels, and other interesting variables. 
	The files are easily accessible and well-documented, with the most recent dataset spanning from 2009-2018 and detailed codebooks available for each geographic grouping level. Their methodology is explained on their website. We downloaded the seda_cov_geodist_long_4.1 and seda_geodist_long_gcs_4.1 files. The initial datafiles are quite large (~700,000 and ~1,200,000 observations, respectively), so even though they are very nicely organized and polished, we were not able to upload them to our repository without some compressing. We were able to collapse each file by year and district. Instead of having an observation for six or seven different grade levels for each year for each district, there was only one observation for each district per year, taking the mean for each selected column across all grades. We also removed some of the variable columns that seemed less relevant to what we were thinking about for potential questions–mostly related to how certain covariates like poverty and race interact and how they might affect test scores. With these edits, we were able to get the files to a size that could be easily shared while still containing huge amounts of relevant information for any potential education inequality related project we might choose to do. 

**Option 2: US police shooting dataset**

https://www.kaggle.com/datasets/ahsen1330/us-police-shootings?resource=download

  The dataset was collected from Kaggle.com, and the dataset comprises records of police shooting incidents in the United States, including a total of 4896 rows, each representing an individual case, and 15 columns, which document various attributes associated with each incident, such as the date, manner of death, and demographics of the individual involved (including age, gender, and race), etc. 
  Moreover, we can clean the dataset by organizing variables, such as the manner of death and types of arms, to numerical data and filter out the rows that contain missing values. In exploring this data, the primary goal is to examine and analyze racial disparities and criminal justice within the context of police shootings. Anticipated challenges include navigating through potential biases in data reporting and incomplete information about individual cases.

**Option 3: Health Insurance Coverage in the US in 2022**

https://www.census.gov/library/publications/2023/demo/p60-281.html

  The dataset "Health Insurance Coverage in the United States: 2022," sourced from the United States Census Bureau, offers detailed insights into the health insurance landscape across the nation for the year 2022. It includes information on various aspects of health insurance coverage, such as the number of insured individuals, coverage rates, types of insurance (e.g., private, public), demographic breakdowns, work experience, education level, income-to-poverty ratio, and incomes per household. We can utilize this dataset to conduct analysis aimed at understanding patterns of health insurance coverage, identifying populations with high rates of uninsurance, assessing the impact of policy changes on coverage rates, and exploring disparities in access to health care services. Moreover, we can investigate the relationship between health insurance coverage and health outcomes, healthcare utilization patterns, and financial burden due to medical expenses. One challenge to using this data is the amount of cleaning necessary to get this into a usable format. This data is not in a clear format so our ability to upload it may be compromised. 
