<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Group 10">
<meta name="dcterms.date" content="2024-04-08">

<title>MA [46]15 Final Project Group 10 - Blog post 4: Exploring the Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">MA [46]15 Final Project Group 10</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../big_picture.html" rel="" target="">
 <span class="menu-text">Big Picture</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../analysis.html" rel="" target="">
 <span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../data.html" rel="" target="">
 <span class="menu-text">Data</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Blog post 4: Exploring the Data</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Group 10 </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 8, 2024</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">April 8, 2024</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="our-trends" class="level2">
<h2 class="anchored" data-anchor-id="our-trends">Our Trends</h2>
<p>As seen in blog post 3, race was a predictor variable in the scores seen in students. Economic status is another. We want to see how these two variables work together, rather than individually like we did last week.</p>
<hr>
</section>
<section id="more-exploration" class="level2">
<h2 class="anchored" data-anchor-id="more-exploration">More Exploration</h2>
<p>Our regression model predicts the average test score (mn_score_all) based on subgroup-specific test scores, including those for Asian (mn_score_asn), Black (mn_score_blk), economically challenged (mn_score_ecd), female (mn_score_fem), Hispanic (mn_score_hsp), male (mn_score_male), multiracial (mn_score_mtr), and white (mn_score_wht) students. Each coefficient (β) represents the expected change in the average test score for a one-unit change in the corresponding subgroup’s test score. We anticipate identifying significant associations between subgroup-specific performance and the overall average test score. Our model’s goodness of fit will be evaluated using metrics such as R-squared and the F-statistic’s significance, while residual plots will ensure adherence to model assumptions.</p>
<hr>
</section>
<section id="linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-model">Linear regression model</h2>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mn_score_all ~ mn_score_asn + mn_score_blk + mn_score_ecd + 
    mn_score_fem + mn_score_hsp + mn_score_male + mn_score_mtr + 
    mn_score_wht, data = cleaned_seda)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.149243 -0.001161  0.000157  0.001379  0.116629 

Coefficients:
                Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)   -0.0006510  0.0002197   -2.963  0.00306 ** 
mn_score_asn   0.0002542  0.0001933    1.315  0.18852    
mn_score_blk   0.0004158  0.0004016    1.035  0.30058    
mn_score_ecd  -0.0008749  0.0006534   -1.339  0.18058    
mn_score_fem   0.4919088  0.0005186  948.496  &lt; 2e-16 ***
mn_score_hsp  -0.0003652  0.0004426   -0.825  0.40926    
mn_score_male  0.5055422  0.0004796 1054.161  &lt; 2e-16 ***
mn_score_mtr  -0.0001177  0.0003305   -0.356  0.72171    
mn_score_wht   0.0010162  0.0003667    2.771  0.00559 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.006255 on 11423 degrees of freedom
  (220146 observations deleted due to missingness)
Multiple R-squared:  0.9997,    Adjusted R-squared:  0.9997 
F-statistic: 4.84e+06 on 8 and 11423 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The summary output of the regression model demonstrates an exceptional fit to the data, with a remarkably low residual standard error of 0.006255, indicating minimal unexplained variability in the dependent variable. The multiple R-squared value of 0.9997 suggests that nearly all of the variance in the dependent variable is accounted for by the independent variables included in the model, while the adjusted R-squared value confirms this finding, adjusting for the number of predictors. The F-statistic is impressively large at 4.84e+06, with an associated p-value of less than 2.2e-16, providing strong evidence of the model’s overall significance. However, it’s noteworthy that not all coefficient estimates are statistically significant at the 5% level, suggesting that while the model as a whole is highly significant, individual predictors may not contribute significantly to explaining the variability in the dependent variable. Despite this, the model still offers valuable insights into the relationship between subgroup-specific test scores and overall average test performance.</p>
<hr>
</section>
<section id="residuals-and-related-statistics-table" class="level2">
<h2 class="anchored" data-anchor-id="residuals-and-related-statistics-table">Residuals and Related Statistics Table:</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">.rownames</th>
<th style="text-align: right;">mn_score_all</th>
<th style="text-align: right;">mn_score_asn</th>
<th style="text-align: right;">mn_score_blk</th>
<th style="text-align: right;">mn_score_ecd</th>
<th style="text-align: right;">mn_score_fem</th>
<th style="text-align: right;">mn_score_hsp</th>
<th style="text-align: right;">mn_score_male</th>
<th style="text-align: right;">mn_score_mtr</th>
<th style="text-align: right;">mn_score_wht</th>
<th style="text-align: right;">.fitted</th>
<th style="text-align: right;">.resid</th>
<th style="text-align: right;">.hat</th>
<th style="text-align: right;">.sigma</th>
<th style="text-align: right;">.cooksd</th>
<th style="text-align: right;">.std.resid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">107</td>
<td style="text-align: right;">0.1134292</td>
<td style="text-align: right;">0.9829746</td>
<td style="text-align: right;">-0.2983284</td>
<td style="text-align: right;">-0.3294385</td>
<td style="text-align: right;">0.1148855</td>
<td style="text-align: right;">-0.3626843</td>
<td style="text-align: right;">0.1136410</td>
<td style="text-align: right;">0.2805765</td>
<td style="text-align: right;">0.0495640</td>
<td style="text-align: right;">0.1138764</td>
<td style="text-align: right;">-0.0004472</td>
<td style="text-align: right;">0.0008911</td>
<td style="text-align: right;">0.0062549</td>
<td style="text-align: right;">0.0000005</td>
<td style="text-align: right;">-0.0715364</td>
</tr>
<tr class="even">
<td style="text-align: left;">108</td>
<td style="text-align: right;">0.0760754</td>
<td style="text-align: right;">0.7291931</td>
<td style="text-align: right;">-0.2113104</td>
<td style="text-align: right;">-0.3534027</td>
<td style="text-align: right;">0.1631109</td>
<td style="text-align: right;">-0.3716772</td>
<td style="text-align: right;">-0.0106456</td>
<td style="text-align: right;">0.3620487</td>
<td style="text-align: right;">0.1882159</td>
<td style="text-align: right;">0.0748940</td>
<td style="text-align: right;">0.0011814</td>
<td style="text-align: right;">0.0005812</td>
<td style="text-align: right;">0.0062549</td>
<td style="text-align: right;">0.0000023</td>
<td style="text-align: right;">0.1889416</td>
</tr>
<tr class="odd">
<td style="text-align: left;">109</td>
<td style="text-align: right;">0.1112676</td>
<td style="text-align: right;">0.9153073</td>
<td style="text-align: right;">-0.2558291</td>
<td style="text-align: right;">-0.3115971</td>
<td style="text-align: right;">0.1165555</td>
<td style="text-align: right;">-0.3414314</td>
<td style="text-align: right;">0.1079094</td>
<td style="text-align: right;">0.2338559</td>
<td style="text-align: right;">0.1268593</td>
<td style="text-align: right;">0.1118614</td>
<td style="text-align: right;">-0.0005938</td>
<td style="text-align: right;">0.0006353</td>
<td style="text-align: right;">0.0062549</td>
<td style="text-align: right;">0.0000006</td>
<td style="text-align: right;">-0.0949690</td>
</tr>
<tr class="even">
<td style="text-align: left;">110</td>
<td style="text-align: right;">0.1713191</td>
<td style="text-align: right;">0.7911062</td>
<td style="text-align: right;">-0.1383624</td>
<td style="text-align: right;">-0.2519623</td>
<td style="text-align: right;">0.2570116</td>
<td style="text-align: right;">-0.2600592</td>
<td style="text-align: right;">0.0839315</td>
<td style="text-align: right;">0.4764108</td>
<td style="text-align: right;">0.2867727</td>
<td style="text-align: right;">0.1689005</td>
<td style="text-align: right;">0.0024186</td>
<td style="text-align: right;">0.0005101</td>
<td style="text-align: right;">0.0062548</td>
<td style="text-align: right;">0.0000085</td>
<td style="text-align: right;">0.3867932</td>
</tr>
<tr class="odd">
<td style="text-align: left;">111</td>
<td style="text-align: right;">0.2622078</td>
<td style="text-align: right;">0.8875326</td>
<td style="text-align: right;">-0.0974942</td>
<td style="text-align: right;">-0.1784335</td>
<td style="text-align: right;">0.4118255</td>
<td style="text-align: right;">-0.1631456</td>
<td style="text-align: right;">0.0996092</td>
<td style="text-align: right;">0.5844247</td>
<td style="text-align: right;">0.3390900</td>
<td style="text-align: right;">0.2529628</td>
<td style="text-align: right;">0.0092450</td>
<td style="text-align: right;">0.0006936</td>
<td style="text-align: right;">0.0062543</td>
<td style="text-align: right;">0.0001686</td>
<td style="text-align: right;">1.4786191</td>
</tr>
<tr class="even">
<td style="text-align: left;">112</td>
<td style="text-align: right;">0.1454739</td>
<td style="text-align: right;">0.8836713</td>
<td style="text-align: right;">-0.2634955</td>
<td style="text-align: right;">-0.3270029</td>
<td style="text-align: right;">0.1728129</td>
<td style="text-align: right;">-0.3292740</td>
<td style="text-align: right;">0.1140409</td>
<td style="text-align: right;">0.3294725</td>
<td style="text-align: right;">0.1872683</td>
<td style="text-align: right;">0.1426826</td>
<td style="text-align: right;">0.0027913</td>
<td style="text-align: right;">0.0005490</td>
<td style="text-align: right;">0.0062548</td>
<td style="text-align: right;">0.0000122</td>
<td style="text-align: right;">0.4464006</td>
</tr>
</tbody>
</table>
</div>
</div>
<hr>
</section>
<section id="residual-plot" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot">Residual Plot</h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="blog-4-exploring-the-data_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Residuals vs.&nbsp;Fitted plot signals an excellent fit of the regression model to the data. This close alignment indicates minimal discrepancies between predicted and observed values, while the consistent spread of residuals suggests uniform variability across different levels of the independent variables. With no discernible patterns, the model accurately captures underlying relationships without systematic errors, meeting key assumptions of linear regression. However, it’s worth noting the presence of some visible leverage points in the data.</p>
<hr>
</section>
<section id="summary-tables" class="level2">
<h2 class="anchored" data-anchor-id="summary-tables">Summary Tables</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   district              year         state             subject         
 Length:231578      Min.   :2009   Length:231578      Length:231578     
 Class :character   1st Qu.:2011   Class :character   Class :character  
 Mode  :character   Median :2013   Mode  :character   Mode  :character  
                    Mean   :2013                                        
                    3rd Qu.:2016                                        
                    Max.   :2018                                        
                                                                        
  mn_score_all      numstu_all       mn_score_asn      numstu_asn      
 Min.   :-3.735   Min.   :    1.0   Min.   :-2.92    Min.   :    1.00  
 1st Qu.:-0.198   1st Qu.:   35.0   1st Qu.: 0.26    1st Qu.:    2.00  
 Median : 0.030   Median :   92.5   Median : 0.60    Median :    3.83  
 Mean   : 0.025   Mean   :  290.5   Mean   : 0.59    Mean   :   29.22  
 3rd Qu.: 0.249   3rd Qu.:  237.5   3rd Qu.: 0.93    3rd Qu.:   14.00  
 Max.   : 2.865   Max.   :74519.0   Max.   : 2.79    Max.   :11901.33  
 NA's   :23209    NA's   :14        NA's   :204226   NA's   :119983    
  mn_score_blk      numstu_blk        mn_score_ecd     numstu_ecd      
 Min.   :-3.40    Min.   :    1.00   Min.   :-3.55   Min.   :    1.00  
 1st Qu.:-0.63    1st Qu.:    2.25   1st Qu.:-0.42   1st Qu.:   15.00  
 Median :-0.45    Median :    6.25   Median :-0.24   Median :   38.33  
 Mean   :-0.44    Mean   :   76.19   Mean   :-0.26   Mean   :  157.82  
 3rd Qu.:-0.25    3rd Qu.:   35.33   3rd Qu.:-0.08   3rd Qu.:  105.17  
 Max.   : 1.16    Max.   :21703.67   Max.   : 1.24   Max.   :61479.33  
 NA's   :180011   NA's   :92324      NA's   :61878   NA's   :5933      
  mn_score_fem     numstu_fem        mn_score_hsp      numstu_hsp      
 Min.   :-2.33   Min.   :    1.00   Min.   :-2.36    Min.   :    1.00  
 1st Qu.:-0.13   1st Qu.:   17.50   1st Qu.:-0.47    1st Qu.:    2.67  
 Median : 0.10   Median :   45.67   Median :-0.28    Median :    7.20  
 Mean   : 0.10   Mean   :  142.82   Mean   :-0.27    Mean   :   87.50  
 3rd Qu.: 0.32   3rd Qu.:  116.67   3rd Qu.:-0.07    3rd Qu.:   31.00  
 Max.   : 1.99   Max.   :36852.67   Max.   : 1.29    Max.   :38164.75  
 NA's   :51590   NA's   :2566       NA's   :163129   NA's   :45649     
 mn_score_male    numstu_male        mn_score_mtr      numstu_mtr     
 Min.   :-3.63   Min.   :    1.00   Min.   :-1.99    Min.   :   1.00  
 1st Qu.:-0.26   1st Qu.:   18.33   1st Qu.:-0.17    1st Qu.:   2.00  
 Median :-0.03   Median :   47.83   Median : 0.05    Median :   4.00  
 Mean   :-0.03   Mean   :  149.41   Mean   : 0.08    Mean   :  13.04  
 3rd Qu.: 0.21   3rd Qu.:  122.50   3rd Qu.: 0.30    3rd Qu.:  10.17  
 Max.   : 1.88   Max.   :37666.33   Max.   : 1.75    Max.   :1904.00  
 NA's   :49363   NA's   :2008       NA's   :207528   NA's   :107040   
   numstu_nec        mn_score_wht     numstu_wht          pernam        
 Min.   :    1.00   Min.   :-1.96   Min.   :    1.0   Min.   :0.000000  
 1st Qu.:   16.33   1st Qu.:-0.05   1st Qu.:   23.2   1st Qu.:0.000000  
 Median :   45.67   Median : 0.14   Median :   64.0   Median :0.002287  
 Mean   :  140.00   Mean   : 0.15   Mean   :  147.5   Mean   :0.030611  
 3rd Qu.:  123.17   3rd Qu.: 0.35   3rd Qu.:  155.7   3rd Qu.:0.007715  
 Max.   :19079.33   Max.   : 1.88   Max.   :11594.3   Max.   :1.000000  
 NA's   :10745      NA's   :42345   NA's   :3927                        
     perasn              perhsp            perblk             perwht      
 Min.   :0.0000000   Min.   :0.00000   Min.   :0.000000   Min.   :0.0000  
 1st Qu.:0.0003241   1st Qu.:0.01727   1st Qu.:0.004082   1st Qu.:0.5935  
 Median :0.0060004   Median :0.04780   Median :0.014202   Median :0.8551  
 Mean   :0.0200166   Mean   :0.13648   Mean   :0.076236   Mean   :0.7367  
 3rd Qu.:0.0169583   3rd Qu.:0.15038   3rd Qu.:0.052917   3rd Qu.:0.9492  
 Max.   :1.0000000   Max.   :1.00000   Max.   :1.000000   Max.   :1.0000  
                                                                          
     perfl              perecd          perell          perspeced     
 Min.   :0.001393   Min.   :0.003   Min.   :0.00000   Min.   :0.0000  
 1st Qu.:0.246492   1st Qu.:0.344   1st Qu.:0.00000   1st Qu.:0.1083  
 Median :0.387229   Median :0.500   Median :0.00922   Median :0.1356  
 Mean   :0.405621   Mean   :0.502   Mean   :0.04227   Mean   :0.1381  
 3rd Qu.:0.545455   3rd Qu.:0.654   3rd Qu.:0.04190   3rd Qu.:0.1655  
 Max.   :0.994910   Max.   :1.000   Max.   :1.00000   Max.   :1.2639  
                    NA's   :3246    NA's   :168       NA's   :168     
    totenrl            unempall        snapall      single_momall  
 Min.   :    0.80   Min.   :0.000   Min.   :0.000   Min.   :0.002  
 1st Qu.:   35.50   1st Qu.:0.054   1st Qu.:0.057   1st Qu.:0.109  
 Median :   93.33   Median :0.070   Median :0.096   Median :0.142  
 Mean   :  294.20   Mean   :0.072   Mean   :0.105   Mean   :0.151  
 3rd Qu.:  240.50   3rd Qu.:0.087   3rd Qu.:0.142   3rd Qu.:0.181  
 Max.   :74619.83   Max.   :0.357   Max.   :0.524   Max.   :0.615  
                    NA's   :6235    NA's   :6235    NA's   :6235   </code></pre>
</div>
</div>
<hr>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>